server:
  port: 8081

spring:

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60000

  graphql:
    graphiql:
      enabled: true

glossary:
  path-to-init-data: ./data/init-glossary.csv
  init-data-separator: ;
