version: '2.4'
services:
  redis:
    platform: linux/x86_64
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
      - "8001:8001"

  glossary:
    build:
      context: .
      dockerfile: Dockerfile
    image: glossary:latest
    environment:
      - SPRING_REDIS_HOST=redis
    volumes:
      - ./data/glossary:/data
    depends_on:
      - redis
    ports:
      - "8080:8080"