version: '2.4'
services:
  redis:
    platform: linux/x86_64
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
      - "8001:8001"

  glossary-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: glossary-backend:latest
    environment:
      - SPRING_REDIS_HOST=redis
    volumes:
      - ./data/glossary:/data
    depends_on:
      - redis
    ports:
      - "8081:8081"

  glossary-frontend:
    build:
      context: ../glossary-frontend
      dockerfile: Dockerfile
    image: glossary-frontend:latest
    depends_on:
      - glossary-backend
    ports:
      - "80:80"

